// const idade = "20"
// const idade2 = 12
// document.getElementById("Titulo")


// let N1 = 20;
// let N2 = 10;

// let operacao = '.';
// let resultado;

// switch (operacao){
//     case '/':
//         resultado = N1/N2;
//         break;
//     case '+':
//         resultado = N1+N2;
//         break;
//     case '-':
//         resultado = N1 - N2;
//         break;
//     case '*':
//         resultado = N1 * N2;
//         break;
//         default:
//             resultado = "Operação Invalida"            
// }



// if(idade <= 18 && idade >= 12){
//     response = "adolecente"
// }
// else if (idade > 18 && idade <20){
//     response = "adulto medio"
// }
// else if(idade > 18 ){
//     response = "adulto"
// }
// else {
//     response = "menor"
// }


//     const num1 = document.getElementById("num1")
//     const num2 = document.getElementById("num2")
    
// Titulo.innerHTML = resultado

// //